version: '3'
services:
  # client:
  #   container_name: habit-tracker
  #   build: ./client
  #   image: debug_client
  #   ports: 
  #     - 8080:8080
  #   working_dir: /code
  #   volumes:
  #     - type: bind
  #       source: ./client
  #       target: /code
  #   command: bash -c "npm run bundle"
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=postpassword
      - PGDATABASE=habittracking
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm run seedDev && npm run dev"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=habittracking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postpassword
volumes:
  dbdata: